name: Generate GitHub Access Tokens
description: Generates a GitHub access token using a custom API endpoint (with SigV4 authentication) and assigns the GitHub access token to an environment variable.

inputs:
  invoke-url:
    description: URL of the custom API endpoint (with SigV4 authentication)
    required: true
  region:
    description: AWS region of the custom API endpoint
    required: true
  configuration-name:
    description: Name of the configuration passed to custom API endpoint as well as the name of the environment variable to which the access token will be assigned
    required: true

runs:
  using: composite

  steps:
    - name: Install dependencies for macOS
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install jq

    - name: Generate GitHub access token and assign it to environment variable
      shell: bash
      run: |
        curl \
          --user "${{ env.AWS_ACCESS_KEY_ID }}":"${{ env.AWS_SECRET_ACCESS_KEY }}" \
          --aws-sigv4 "aws:amz:${{ inputs.region }}:execute-api" \
          -X POST \
          -H "x-amz-security-token: ${{ env.AWS_SESSION_TOKEN }}" \
          ${{ inputs.invoke-url }}/configurations/${{ inputs.configuration-name }}/github-access-tokens \
          | jq -r '"echo \"${{ inputs.configuration-name }}=\(.token)\" >> $GITHUB_ENV"' \
          | bash
